exp_name: baseline_gpu_smoke

seed: 1
cuda: true
torch_deterministic: true

env_id: PushCube-v1

obs_mode: state
reward_mode: normalized_dense
sim_backend: physx_cuda
control_mode: pd_joint_delta_pos

num_envs: 2048
num_eval_envs: 16

num_steps: 20
total_timesteps: 2000000

learning_rate: 0.0003
gamma: 0.8
gae_lambda: 0.9

num_minibatches: 32
update_epochs: 8

norm_adv: true
clip_coef: 0.2
clip_vloss: false

ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: 0.1

anneal_lr: false
reward_scale: 1.0

eval_freq: 10
num_eval_steps: 200

partial_reset: true
eval_partial_reset: false

reconfiguration_freq: null
eval_reconfiguration_freq: 1

capture_video: false
save_model: true

encoder_type: state