exp_name: depth_goal_dr_gpu_smoke

seed: 1

env_id: PushCubeDepthGoalDR-v1

obs_mode: depth
encoder_type: depth_goal

sim_backend: physx_cuda
cuda: true

num_envs: 16
num_eval_envs: 4

num_steps: 20
total_timesteps: 3200

num_minibatches: 4
update_epochs: 4

capture_video: false
save_model: true