exp_name: depth_goal_gpu_seed2

seed: 2

env_id: PushCubeDepthGoal-v1

obs_mode: depth
encoder_type: depth_goal

sim_backend: physx_cuda
cuda: true

num_envs: 2048
num_eval_envs: 16

num_steps: 20
total_timesteps: 2000000

learning_rate: 0.0003
gamma: 0.8
gae_lambda: 0.9

num_minibatches: 32
update_epochs: 8
