# Experiment
exp_name: ppo_state_cpu
seed: 1

# Device
cuda: false
torch_deterministic: true

# Environment
env_id: PushCube-v1
obs_mode: state
reward_mode: normalized_dense
sim_backend: physx_cpu
control_mode: pd_joint_delta_pos

num_envs: 1
num_eval_envs: 1

reconfiguration_freq: null
eval_reconfiguration_freq: 1

partial_reset: true
eval_partial_reset: false

# PPO
total_timesteps: 300000
learning_rate: 0.0003

num_steps: 50
num_eval_steps: 200

gamma: 0.8
gae_lambda: 0.9

num_minibatches: 2
update_epochs: 4

norm_adv: true
clip_coef: 0.2
clip_vloss: false

ent_coef: 0.0
vf_coef: 0.5

max_grad_norm: 0.5
target_kl: 0.1

reward_scale: 1.0

# Evaluation
eval_freq: 200

# Logging
capture_video: false
save_model: true
track: false

save_train_video_freq: null

anneal_lr: false
finite_horizon_gae: false